# Generated by Django 3.0.6 on 2021-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_auto_20210116_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='aprovado',
            field=models.BooleanField(default=1, verbose_name='Aprovado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receitas',
            name='conferido',
            field=models.BooleanField(default=1, verbose_name='Conferido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receitas',
            name='notificado',
            field=models.BooleanField(default=1, verbose_name='Notificado'),
            preserve_default=False,
        ),
    ]
