# Generated by Django 3.0.6 on 2021-01-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_remove_receitas_repasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='repasse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Repasse - NAP'),
        ),
    ]
