# Generated by Django 3.0.6 on 2021-01-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0009_receitas_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='empresa',
        ),
    ]
