# Generated by Django 5.1.4 on 2025-01-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0011_receitas_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='departamento',
        ),
    ]
