# Generated by Django 3.0.6 on 2020-06-20 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_antiga', '0003_auto_20181225_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrousuarios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='teste',
            options={'managed': False},
        ),
    ]
