# Generated by Django 3.0.6 on 2020-06-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_antiga', '0004_auto_20200620_2034'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teste',
            table='app_antiga_teste',
        ),
    ]
