# Generated by Django 3.0.6 on 2021-01-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='equipamento',
            field=models.CharField(default=1, max_length=100, verbose_name='Equipamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario',
            field=models.CharField(default=1, max_length=100, verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
