# Generated by Django 3.0.6 on 2021-01-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20210111_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('analista de comunicação', 'Analista de Comunicação'), ('almoxarife', 'Almoxarife'), ('assistente administrativo', 'Assistente Administrativo'), ('assistente de rh', 'Assistente de RH'), ('atendente de restaurante', 'Atendente de Restaurante')], max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='equipamento',
            field=models.CharField(choices=[('restaurante popular ressaca', 'Restaurante Popular Ressaca'), ('restaurante popular eldorado', 'Restaurante Popular Eldorado'), ('restaurante popular nova contagem', 'Restaurante Popular Nova Contagem'), ('cozinha comunitária nova contagem', 'Cozinha Comunitária Nova Contagem'), ('cozinha nacional', 'Cozinha Nacional')], max_length=100, verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nivel',
            field=models.CharField(choices=[('i', 'I'), ('ii', 'II'), ('iii', 'III'), ('iv', 'IV'), ('v', 'V'), ('vi', 'VI'), ('vii', 'VII'), ('viii', 'VIII'), ('ix', 'IX'), ('x', 'X'), ('xi', 'XI'), ('xii', 'XII')], max_length=10, verbose_name='Cargo'),
        ),
    ]
