# Generated by Django 3.0.6 on 2021-01-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_auto_20210111_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nivel',
            field=models.CharField(blank=True, choices=[('--', '--'), ('i', 'I'), ('ii', 'II'), ('iii', 'III'), ('iv', 'IV'), ('v', 'V'), ('vi', 'VI'), ('vii', 'VII'), ('viii', 'VIII'), ('ix', 'IX'), ('x', 'X'), ('xi', 'XI'), ('xii', 'XII')], max_length=10, null=True, verbose_name='Nível'),
        ),
    ]
