# Generated by Django 3.0.6 on 2021-01-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_auto_20210112_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='avisoPrevio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aviso Prévio'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='avos13Salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1/12 avos 13º Salário'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='avosFerias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1/12 avos Férias'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='avosTercoFerias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1/12 avos 1/3 Férias'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fgts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='FGTS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='inss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='INSS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='multafgts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Multa FGTS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='totalRescisao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Rescisão'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='totalVerbaRescisoria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Verba Rescisória'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('--', '--'), ('administrador(a)', 'Administrador(a)'), ('almoxarife', 'Almoxarife'), ('analista de comunicação', 'Analista de Comunicação'), ('analista de processos', 'Analista de Processos'), ('assistente administrativo', 'Assistente Administrativo'), ('assistente de rh', 'Assistente de RH'), ('atendente de restaurante', 'Atendente de Restaurante'), ('auxiliar de coordenação', 'Auxiliar de Coordenação'), ('auxiliar de cozinha', 'Auxiliar de Cozinha'), ('auxiliar de escritório', 'Auxiliar de Escritório'), ('auxiliar de serviços gerais', 'Auxiliar de Serviços Gerais'), ('caixa', 'Caixa'), ('chefe de cozinha', 'Chefe de Cozinha'), ('comissionado(a)', 'Comissionado(a)'), ('contratado(a)', 'Contratado(a)'), ('coordenador(a)', 'Coordenador(a)'), ('coordenador(a) administrativo financeiro', 'Coordenador(a) Administrativo Financeiro'), ('coordenador(a) de eventos', 'Coordenador(a) de Eventos'), ('coordenador(a) de logística', 'Coordenador(a) de logística'), ('coordenador(a) de projetos', 'Coordenador(a) de Projetos'), ('cozinheiro(a)', 'Cozinheiro(a)'), ('diretor(a) de abastecimento', 'Diretor(a) de Abastecimento'), ('efetivo(a)', 'Efetivo(a)'), ('encarregado(a) de manutenção', 'Encarregado(a) de Manutenção'), ('gerente administrativo', 'Gerente Administrativo'), ('gerente administrativo financeiro', 'Gerente Administrativo Financeiro'), ('gerente de prestação de contas', 'Gerente de Prestação de Contas'), ('gerente de qualidade', 'Gerente de Qualidade'), ('gerente financeiro', 'Gerente Financeiro'), ('gestor(a)', 'Gestor(a)'), ('motorista', 'Motorista'), ('nutricionista', 'Nutricionista'), ('operador(a) de manutenção', 'Operador(a) de Manutenção'), ('político', 'Político'), ('saladeira(o)', 'Saladeira(o)'), ('supervisor(a) de manutenção', 'Supervisor(a) de Manutenção'), ('supervisor(a) de serviços gerais', 'Supervisor(a) de Serviços Gerais'), ('técnico de contabilidade', 'Técnico de Contabilidade')], max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='equipamento',
            field=models.CharField(blank=True, choices=[('--', '--'), ('cozinha comunitária nacional', 'Cozinha Comunitária Nacional'), ('cozinha comunitária nova contagem', 'Cozinha Comunitária Nova Contagem'), ('restaurante popular eldorado', 'Restaurante Popular Eldorado'), ('restaurante popular nova contagem', 'Restaurante Popular Nova Contagem'), ('restaurante popular ressaca', 'Restaurante Popular Ressaca')], max_length=100, null=True, verbose_name='Equipamento'),
        ),
    ]
