# Generated by Django 3.0.6 on 2021-01-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0013_auto_20210120_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nivel',
            field=models.CharField(blank=True, choices=[('--', '--'), ('i', 'I'), ('ii', 'II'), ('iii', 'III'), ('iv', 'IV'), ('v', 'V'), ('vi', 'VI'), ('vii', 'VII'), ('viii', 'VIII'), ('ix', 'IX'), ('x', 'X'), ('xi', 'XI'), ('xii', 'XII'), ('dam 01', 'DAM 01'), ('dam 02', 'DAM 02'), ('dam 03', 'DAM 03'), ('dam 04', 'DAM 04'), ('dam 05', 'DAM 05'), ('dam 06', 'DAM 06'), ('dam 07', 'DAM 07'), ('dam 08', 'DAM 08'), ('dam 09', 'DAM 09'), ('dam 10', 'DAM 10'), ('dam 11', 'DAM 11'), ('dam 12', 'DAM 12'), ('dam 13', 'DAM 13'), ('dam 14', 'DAM 14'), ('dam 15', 'DAM 15'), ('dam 16', 'DAM 16'), ('dam 17', 'DAM 17'), ('dam 18', 'DAM 18'), ('dam 19', 'DAM 19'), ('dam 20', 'DAM 20')], max_length=10, null=True, verbose_name='Nível'),
        ),
    ]
