# Generated by Django 4.2.2 on 2023-06-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0014_auto_20210121_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('--', '--'), ('administrador(a)', 'Administrador(a)'), ('administrador(a) do Sistema', 'Administrador(a) do Sistema'), ('almoxarife', 'Almoxarife'), ('analista de comunicação', 'Analista de Comunicação'), ('analista de processos', 'Analista de Processos'), ('assistente administrativo', 'Assistente Administrativo'), ('assistente de rh', 'Assistente de RH'), ('atendente de restaurante', 'Atendente de Restaurante'), ('auxiliar de coordenação', 'Auxiliar de Coordenação'), ('auxiliar de cozinha', 'Auxiliar de Cozinha'), ('auxiliar de escritório', 'Auxiliar de Escritório'), ('auxiliar de serviços gerais', 'Auxiliar de Serviços Gerais'), ('caixa', 'Caixa'), ('chefe de cozinha', 'Chefe de Cozinha'), ('comissionado(a)', 'Comissionado(a)'), ('contratado(a)', 'Contratado(a)'), ('coordenador(a)', 'Coordenador(a)'), ('coordenador(a) administrativo financeiro', 'Coordenador(a) Administrativo Financeiro'), ('coordenador(a) de eventos', 'Coordenador(a) de Eventos'), ('coordenador(a) de logística', 'Coordenador(a) de logística'), ('coordenador(a) de projetos', 'Coordenador(a) de Projetos'), ('cozinheiro(a)', 'Cozinheiro(a)'), ('diretor(a) de abastecimento', 'Diretor(a) de Abastecimento'), ('efetivo(a)', 'Efetivo(a)'), ('encarregado(a) de manutenção', 'Encarregado(a) de Manutenção'), ('gerente administrativo', 'Gerente Administrativo'), ('gerente administrativo financeiro', 'Gerente Administrativo Financeiro'), ('gerente de prestação de contas', 'Gerente de Prestação de Contas'), ('gerente de qualidade', 'Gerente de Qualidade'), ('gerente financeiro', 'Gerente Financeiro'), ('gestor(a)', 'Gestor(a)'), ('motorista', 'Motorista'), ('nutricionista', 'Nutricionista'), ('operador(a) de manutenção', 'Operador(a) de Manutenção'), ('político', 'Político'), ('saladeira(o)', 'Saladeira(o)'), ('supervisor(a) de manutenção', 'Supervisor(a) de Manutenção'), ('supervisor(a) de serviços gerais', 'Supervisor(a) de Serviços Gerais'), ('técnico de contabilidade', 'Técnico de Contabilidade')], max_length=100, null=True, verbose_name='Cargo'),
        ),
    ]
