# Generated by Django 4.2.2 on 2023-07-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_curso_obs'),
        ('funcionarios', '0017_remove_funcionario_curso_funcionario_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='curso',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='curso',
            field=models.ManyToManyField(to='curso.curso', verbose_name='Cursos Realizados'),
        ),
    ]
