# Generated by Django 5.1.4 on 2025-01-03 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia3', '0009_remove_conferencia3_departamento_and_more'),
        ('funcionarios', '0020_funcionario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='conferencia3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='conferencia3.conferencia3'),
        ),
    ]
