# Generated by Django 5.1.4 on 2025-01-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0021_funcionario_conferencia3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='conferencia3',
            new_name='credor',
        ),
    ]
