# Generated by Django 5.2.11 on 2026-09-08 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0024_sprint17_ponto_folha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcionario",
            name="conferencia3",
        ),
    ]
