# Generated by Django 5.2.11 on 2026-09-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0028_alter_funcionario_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="cpf_normalizado",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=11,
                null=True,
                unique=True,
                verbose_name="CPF normalizado",
            ),
        ),
    ]
