# Generated by Django 5.2.11 on 2026-10-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0030_alter_funcionario_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Colaborador"),
        ),
    ]
