# Generated by Django 5.2.11 on 2026-10-07 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0031_alter_funcionario_nome"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcionario",
            options={
                "ordering": ["nome"],
                "permissions": [
                    (
                        "view_funcionario_identificacao",
                        "Pode visualizar identificacao e vinculo do colaborador",
                    ),
                    (
                        "change_funcionario_identificacao",
                        "Pode alterar identificacao e vinculo do colaborador",
                    ),
                    (
                        "view_funcionario_dados_pessoais",
                        "Pode visualizar dados pessoais do colaborador",
                    ),
                    (
                        "change_funcionario_dados_pessoais",
                        "Pode alterar dados pessoais do colaborador",
                    ),
                    (
                        "view_funcionario_endereco",
                        "Pode visualizar endereco do colaborador",
                    ),
                    (
                        "change_funcionario_endereco",
                        "Pode alterar endereco do colaborador",
                    ),
                    (
                        "view_funcionario_dados_funcionais",
                        "Pode visualizar dados funcionais do colaborador",
                    ),
                    (
                        "change_funcionario_dados_funcionais",
                        "Pode alterar dados funcionais do colaborador",
                    ),
                    (
                        "view_funcionario_folha",
                        "Pode visualizar dados de folha e bancarios do colaborador",
                    ),
                    (
                        "change_funcionario_folha",
                        "Pode alterar dados de folha e bancarios do colaborador",
                    ),
                    (
                        "view_funcionario_acesso_sistema",
                        "Pode visualizar acesso ao sistema do colaborador",
                    ),
                    (
                        "change_funcionario_acesso_sistema",
                        "Pode alterar acesso ao sistema do colaborador",
                    ),
                ],
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
            },
        ),
    ]
