# Generated by Django 5.2.11 on 2026-10-07 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0016_remove_empresa_conferencia3"),
        ("funcionarios", "0032_alter_funcionario_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["nome"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="funcionario",
            name="cargo_cadastro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="colaboradores",
                to="funcionarios.cargo",
                verbose_name="Cargo",
            ),
        ),
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
                "ordering": ["nome"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="funcionario",
            name="equipamento_cadastro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="colaboradores",
                to="funcionarios.equipamento",
                verbose_name="Equipamento",
            ),
        ),
        migrations.CreateModel(
            name="Nivel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nível",
                "verbose_name_plural": "Níveis",
                "ordering": ["ordem", "nome"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="funcionario",
            name="nivel_cadastro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="colaboradores",
                to="funcionarios.nivel",
                verbose_name="Nível",
            ),
        ),
        migrations.AddConstraint(
            model_name="cargo",
            constraint=models.UniqueConstraint(
                fields=("empresa", "nome"), name="uniq_cargo_empresa_nome"
            ),
        ),
        migrations.AddConstraint(
            model_name="equipamento",
            constraint=models.UniqueConstraint(
                fields=("empresa", "nome"), name="uniq_equipamento_empresa_nome"
            ),
        ),
        migrations.AddConstraint(
            model_name="nivel",
            constraint=models.UniqueConstraint(
                fields=("empresa", "nome"), name="uniq_nivel_empresa_nome"
            ),
        ),
    ]
