# Generated by Django 3.0.6 on 2021-01-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20210111_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='nivel',
            field=models.CharField(choices=[('i', 'I'), ('ii', 'II'), ('iii', 'III'), ('iv', 'CPF'), ('v', 'CPF'), ('vi', 'CPF'), ('vii', 'CPF'), ('viii', 'CPF'), ('ix', 'CPF'), ('x', 'CPF'), ('xi', 'CPF'), ('xii', 'CPF')], default=1, max_length=10, verbose_name='Cargo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('analista de comunicação', 'Analista de Comunicação'), ('almoxarife', 'almoxarife'), ('assistente administrativo', 'Assistente Administrativo'), ('assistente de rh', 'assistente de RH'), ('atendente de restaurante', 'Atendente de Restaurante'), ('', ''), ('', ''), ('', '')], max_length=100, verbose_name='Cargo'),
        ),
    ]
