# Generated by Django 3.0.6 on 2021-01-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_auto_20210111_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='diasTrabalhados',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dias Trabalhados'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salarioBase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Base'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salarioBruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Bruto'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salarioLiquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Líquido'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('--', '--'), ('administrador', 'Administrador'), ('analista de comunicação', 'Analista de Comunicação'), ('almoxarife', 'Almoxarife'), ('assistente administrativo', 'Assistente Administrativo'), ('assistente de rh', 'Assistente de RH'), ('atendente de restaurante', 'Atendente de Restaurante'), ('auxiliar de coordenação', 'Auxiliar de Coordenação')], max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='equipamento',
            field=models.CharField(blank=True, choices=[('--', '--'), ('restaurante popular ressaca', 'Restaurante Popular Ressaca'), ('restaurante popular eldorado', 'Restaurante Popular Eldorado'), ('restaurante popular nova contagem', 'Restaurante Popular Nova Contagem'), ('cozinha comunitária nova contagem', 'Cozinha Comunitária Nova Contagem'), ('cozinha nacional', 'Cozinha Nacional')], max_length=100, null=True, verbose_name='Equipamento'),
        ),
    ]
