# Generated by Django 4.2.2 on 2023-06-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('funcionarios', '0015_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='curso',
            field=models.ManyToManyField(to='curso.curso', verbose_name='Cursos Realizados'),
        ),
    ]
