# Generated by Django 4.2.2 on 2023-07-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_curso_obs'),
        ('funcionarios', '0016_funcionario_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='curso',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curso.curso'),
        ),
    ]
