from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal

class Migration(migrations.Migration):
    dependencies=[("funcionarios","0023_remove_funcionario_credor_funcionario_conferencia3"),("termos","0017_alter_termos_extratosbancarios_and_more"),("auth","0012_alter_user_first_name_max_length")]
    operations=[
        migrations.AddField(model_name="funcionario",name="cpf",field=models.CharField(blank=True,max_length=14,null=True,verbose_name="CPF")),
        migrations.AddField(model_name="funcionario",name="pis_pasep_nit",field=models.CharField(blank=True,max_length=20,null=True,verbose_name="PIS/PASEP/NIT")),
        migrations.AddField(model_name="funcionario",name="data_nascimento",field=models.DateField(blank=True,null=True,verbose_name="Data de nascimento")),
        migrations.AddField(model_name="funcionario",name="tipo_vinculo",field=models.CharField(choices=[("clt","Empregado CLT"),("autonomo","Autônomo / contribuinte individual"),("estagiario","Estagiário"),("bolsista","Bolsista"),("voluntario","Voluntário"),("dirigente_remunerado","Dirigente remunerado"),("dirigente_nao_remunerado","Dirigente não remunerado"),("outro","Outro")],default="clt",max_length=30,verbose_name="Tipo de vínculo")),
        migrations.AddField(model_name="funcionario",name="data_admissao",field=models.DateField(blank=True,null=True,verbose_name="Data de admissão")),
        migrations.AddField(model_name="funcionario",name="data_desligamento",field=models.DateField(blank=True,null=True,verbose_name="Data de desligamento")),
        migrations.AddField(model_name="funcionario",name="jornada_semanal",field=models.DecimalField(decimal_places=2,default=Decimal("44.00"),max_digits=5,verbose_name="Jornada semanal")),
        migrations.AddField(model_name="funcionario",name="divisor_mensal",field=models.PositiveIntegerField(default=220,verbose_name="Divisor mensal")),
        migrations.AddField(model_name="funcionario",name="termo",field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="trabalhadores",to="termos.termos",verbose_name="Termo/parceria")),
        migrations.AddField(model_name="funcionario",name="centro_custo",field=models.CharField(blank=True,max_length=120,null=True,verbose_name="Centro de custo")),
        migrations.AddField(model_name="funcionario",name="banco",field=models.CharField(blank=True,max_length=80,null=True,verbose_name="Banco")),
        migrations.AddField(model_name="funcionario",name="agencia",field=models.CharField(blank=True,max_length=20,null=True,verbose_name="Agência")),
        migrations.AddField(model_name="funcionario",name="conta_bancaria",field=models.CharField(blank=True,max_length=30,null=True,verbose_name="Conta bancária")),
        migrations.CreateModel(name="FolhaPonto",fields=[("id",models.AutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("competencia",models.DateField(help_text="Use o primeiro dia do mês.",verbose_name="Competência")),("horas_previstas",models.DecimalField(decimal_places=2,default=Decimal("0.00"),max_digits=7)),("horas_trabalhadas",models.DecimalField(decimal_places=2,default=Decimal("0.00"),max_digits=7)),("horas_extras",models.DecimalField(decimal_places=2,default=Decimal("0.00"),max_digits=7)),("horas_faltas_atrasos",models.DecimalField(decimal_places=2,default=Decimal("0.00"),max_digits=7,verbose_name="Faltas/atrasos (horas)")),("banco_horas",models.DecimalField(decimal_places=2,default=Decimal("0.00"),max_digits=7)),("observacoes",models.TextField(blank=True)),("status",models.CharField(choices=[("aberta","Aberta"),("fechada","Fechada")],default="aberta",max_length=10)),("fechado_em",models.DateTimeField(blank=True,null=True)),("criado_em",models.DateTimeField(auto_now_add=True)),("atualizado_em",models.DateTimeField(auto_now=True)),("fechado_por",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="folhas_ponto_fechadas",to="auth.user")),("funcionario",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="folhas_ponto",to="funcionarios.funcionario"))],options={"verbose_name":"Folha de ponto","verbose_name_plural":"Folhas de ponto","ordering":["-competencia","funcionario__nome"]}),
        migrations.CreateModel(name="FolhaPagamento",fields=[("id",models.AutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("competencia",models.DateField(help_text="Use o primeiro dia do mês.",verbose_name="Competência")),("salario_base",models.DecimalField(decimal_places=2,max_digits=12)),("adicional_percentual_hora_extra",models.DecimalField(decimal_places=2,default=Decimal("50.00"),max_digits=6,verbose_name="Adicional de hora extra (%)")),("outras_verbas",models.DecimalField(decimal_places=2,default=Decimal("0.00"),max_digits=12,verbose_name="Outros proventos")),("outros_descontos",models.DecimalField(decimal_places=2,default=Decimal("0.00"),max_digits=12)),("inss",models.DecimalField(decimal_places=2,default=Decimal("0.00"),max_digits=12,verbose_name="INSS")),("irrf",models.DecimalField(decimal_places=2,default=Decimal("0.00"),max_digits=12,verbose_name="IRRF")),("vale_transporte",models.DecimalField(decimal_places=2,default=Decimal("0.00"),max_digits=12)),("pensao",models.DecimalField(decimal_places=2,default=Decimal("0.00"),max_digits=12,verbose_name="Pensão")),("observacoes",models.TextField(blank=True)),("status",models.CharField(choices=[("rascunho","Rascunho"),("fechada","Fechada")],default="rascunho",max_length=10)),("fechado_em",models.DateTimeField(blank=True,null=True)),("criado_em",models.DateTimeField(auto_now_add=True)),("atualizado_em",models.DateTimeField(auto_now=True)),("fechado_por",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="folhas_pagamento_fechadas",to="auth.user")),("folha_ponto",models.OneToOneField(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="contracheque",to="funcionarios.folhaponto")),("funcionario",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="folhas_pagamento",to="funcionarios.funcionario"))],options={"verbose_name":"Folha de pagamento","verbose_name_plural":"Folhas de pagamento","ordering":["-competencia","funcionario__nome"]}),
        migrations.AddConstraint(model_name="folhaponto",constraint=models.UniqueConstraint(fields=("funcionario","competencia"),name="uniq_ponto_func_competencia")),
        migrations.AddConstraint(model_name="folhapagamento",constraint=models.UniqueConstraint(fields=("funcionario","competencia"),name="uniq_pagamento_func_competencia")),
    ]
