# Generated by Django 5.2.11 on 2026-08-13 02:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajuda_contextual", "0002_ajudas_iniciais"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ajudacontextual",
            new_name="ajuda_conte_modulo_2b507d_idx",
            old_name="ajuda_conte_modulo_4a4f6b_idx",
        ),
    ]
