# Generated by Django 5.2.11 on 2026-08-22 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoDashboardGrupo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modulo", models.CharField(max_length=50)),
                ("exibir", models.BooleanField(default=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracoes_dashboard",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["grupo__name", "modulo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("grupo", "modulo"), name="uniq_dashboard_grupo_modulo"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoDashboardUsuario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modulo", models.CharField(max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("herdar", "Herdar"),
                            ("mostrar", "Mostrar"),
                            ("ocultar", "Ocultar"),
                        ],
                        default="herdar",
                        max_length=10,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracoes_dashboard",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["usuario__username", "modulo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "modulo"),
                        name="uniq_dashboard_usuario_modulo",
                    )
                ],
            },
        ),
    ]
