# Generated by Django 5.2.11 on 2026-08-22 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoDashboardWidgetGrupo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("widget", models.CharField(max_length=60)),
                ("exibir", models.BooleanField(default=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracoes_widgets_dashboard",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["grupo__name", "widget"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("grupo", "widget"), name="uniq_dashboard_widget_grupo"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoDashboardWidgetUsuario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("widget", models.CharField(max_length=60)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("herdar", "Herdar"),
                            ("mostrar", "Mostrar"),
                            ("ocultar", "Ocultar"),
                        ],
                        default="herdar",
                        max_length=10,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracoes_widgets_dashboard",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["usuario__username", "widget"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "widget"),
                        name="uniq_dashboard_widget_usuario",
                    )
                ],
            },
        ),
    ]
