# Generated by Django 5.2.11 on 2026-09-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_configuracaodashboardwidgetgrupo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SequenciaPseudonimo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("COL", "Colaborador"), ("FOR", "Fornecedor")],
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("ultimo_numero", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Sequencia de pseudonimo",
                "verbose_name_plural": "Sequencias de pseudonimos",
            },
        ),
    ]
