# Generated by Django 5.2.11 on 2026-08-17 01:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("metas", "0002_alter_atualizacaometa_options_and_more"),
        ("termos", "0017_alter_termos_extratosbancarios_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "versao",
                    models.PositiveIntegerField(default=1, verbose_name="Versão"),
                ),
                (
                    "titulo",
                    models.CharField(blank=True, max_length=180, verbose_name="Título"),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("inicial", "Plano inicial"),
                            ("aditivo", "Termo aditivo"),
                            ("remanejamento", "Remanejamento"),
                            ("outra", "Outra alteração"),
                        ],
                        default="inicial",
                        max_length=20,
                        verbose_name="Origem da versão",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("vigente", "Vigente"),
                            ("substituido", "Substituído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "inicio_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Início da vigência"
                    ),
                ),
                (
                    "fim_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim da vigência"
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de aprovação"
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="planos_trabalho/%Y/%m/",
                        verbose_name="Arquivo da versão",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "termo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planos_trabalho_estruturados",
                        to="termos.termos",
                        verbose_name="Termo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Trabalho",
                "verbose_name_plural": "Planos de Trabalho",
                "ordering": ["termo", "-versao"],
            },
        ),
        migrations.CreateModel(
            name="ItemPlanoTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, verbose_name="Código do item"),
                ),
                (
                    "rubrica_nivel_1",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Rubrica nível 1"
                    ),
                ),
                (
                    "rubrica_nivel_2",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Rubrica nível 2"
                    ),
                ),
                (
                    "rubrica_nivel_3",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Rubrica nível 3"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "unidade",
                    models.CharField(blank=True, max_length=50, verbose_name="Unidade"),
                ),
                (
                    "quantidade_prevista",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                        verbose_name="Quantidade prevista",
                    ),
                ),
                (
                    "valor_unitario_previsto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor unitário previsto",
                    ),
                ),
                (
                    "valor_total_previsto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor total previsto",
                    ),
                ),
                (
                    "inicio_execucao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Início previsto da execução",
                    ),
                ),
                (
                    "fim_execucao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim previsto da execução"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "meta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_plano_trabalho",
                        to="metas.metaexecucao",
                        verbose_name="Meta relacionada",
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="planos_trabalho.planotrabalho",
                        verbose_name="Plano de Trabalho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Plano de Trabalho",
                "verbose_name_plural": "Itens do Plano de Trabalho",
                "ordering": ["plano", "codigo"],
            },
        ),
        migrations.AddConstraint(
            model_name="planotrabalho",
            constraint=models.UniqueConstraint(
                fields=("termo", "versao"), name="uniq_plano_termo_versao"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemplanotrabalho",
            constraint=models.UniqueConstraint(
                fields=("plano", "codigo"), name="uniq_item_codigo_por_plano"
            ),
        ),
    ]
