# Generated by Django 5.2.11 on 2026-08-17 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planos_trabalho", "0001_initial"),
        ("termos", "0017_alter_termos_extratosbancarios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planotrabalho",
            name="data_eficacia",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de eficácia da versão"
            ),
        ),
        migrations.AddField(
            model_name="planotrabalho",
            name="instrumento_alteracao",
            field=models.CharField(
                blank=True,
                help_text="Ex.: Termo Aditivo nº 01, autorização de remanejamento ou outro instrumento aplicável.",
                max_length=150,
                verbose_name="Instrumento da alteração",
            ),
        ),
        migrations.AddField(
            model_name="planotrabalho",
            name="justificativa_alteracao",
            field=models.TextField(
                blank=True, verbose_name="Justificativa da alteração"
            ),
        ),
        migrations.AddField(
            model_name="planotrabalho",
            name="versao_anterior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versoes_subsequentes",
                to="planos_trabalho.planotrabalho",
                verbose_name="Versão anterior",
            ),
        ),
        migrations.AddConstraint(
            model_name="planotrabalho",
            constraint=models.UniqueConstraint(
                condition=models.Q(("situacao", "vigente")),
                fields=("termo",),
                name="uniq_plano_vigente_por_termo",
            ),
        ),
    ]
