# Generated by Django 5.2.11 on 2026-08-17 23:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lancamentos", "0002_glosas_sprint16"),
        ("planos_trabalho", "0002_planotrabalho_data_eficacia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VinculoLancamentoItemPlano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("manual", "Vínculo manual"),
                            ("automatico", "Sugestão automática"),
                            ("importacao", "Importação"),
                            ("migracao", "Migração de legado"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Origem do vínculo",
                    ),
                ),
                (
                    "confianca",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Confiança (%)",
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(blank=True, verbose_name="Justificativa"),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Vínculo ativo"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "item_plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_lancamentos",
                        to="planos_trabalho.itemplanotrabalho",
                        verbose_name="Item do Plano de Trabalho",
                    ),
                ),
                (
                    "lancamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_itens_plano",
                        to="lancamentos.lancamento",
                        verbose_name="Lançamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo entre lançamento e item do Plano",
                "verbose_name_plural": "Vínculos entre lançamentos e itens do Plano",
                "ordering": ["-ativo", "-criado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ativo", True)),
                        fields=("lancamento",),
                        name="uniq_item_plano_ativo_por_lancamento",
                    )
                ],
            },
        ),
    ]
