# Generated by Django 5.2.11 on 2026-08-18 00:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planos_trabalho", "0003_vinculolancamentoitemplano"),
    ]

    operations = [
        migrations.AddField(
            model_name="vinculolancamentoitemplano",
            name="quantidade_executada",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0000"))
                ],
                verbose_name="Quantidade executada",
            ),
        ),
        migrations.AddField(
            model_name="vinculolancamentoitemplano",
            name="unidade_executada",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Unidade executada"
            ),
        ),
        migrations.AddField(
            model_name="vinculolancamentoitemplano",
            name="valor_unitario_executado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Valor unitário executado",
            ),
        ),
    ]
