# Generated by Django 3.0.6 on 2021-01-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0004_remove_termos_prestacao'),
        ('prestacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacao',
            name='termos',
            field=models.ManyToManyField(to='termos.Termos'),
        ),
    ]
