# Generated by Django 3.0.6 on 2021-01-25 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_remove_departamento_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestacao', '0002_prestacao_termos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacao',
            name='termos',
        ),
        migrations.AddField(
            model_name='prestacao',
            name='departamentos',
            field=models.ManyToManyField(to='departamentos.Departamento'),
        ),
        migrations.AddField(
            model_name='prestacao',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
