# Generated by Django 4.2.2 on 2023-06-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacao', '0006_auto_20210127_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacao',
            name='numtermo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Termo'),
        ),
    ]
