# Generated by Django 5.2.11 on 2026-09-08 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresas", "0016_remove_empresa_conferencia3"),
        ("prestacao", "0014_vincula_termos_prestacoes"),
        ("termos", "0017_alter_termos_extratosbancarios_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentacaoFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("repasse", "Repasse"),
                            ("deposito_osc", "Deposito OSC"),
                            ("rendimento", "Rendimento"),
                            ("credito_autorizado", "Credito autorizado"),
                            ("resgate_automatico", "Resgate automatico"),
                            ("estorno", "Estorno"),
                            ("aplicacao", "Aplicacao financeira"),
                            ("debito_autorizado", "Debito autorizado"),
                            ("despesa_bancaria", "Despesa bancaria"),
                            ("imposto_renda", "Imposto de renda"),
                            ("iof", "IOF"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=15)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                (
                    "documento",
                    models.FileField(blank=True, null=True, upload_to="financeiro/"),
                ),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "competencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes_financeiras",
                        to="prestacao.competenciaprestacao",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes_financeiras_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes_financeiras",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes_financeiras",
                        to="prestacao.prestacao",
                    ),
                ),
                (
                    "termo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes_financeiras",
                        to="termos.termos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentacao financeira",
                "verbose_name_plural": "Movimentacoes financeiras",
                "ordering": ("data", "id"),
            },
        ),
    ]
