# Generated by Django 5.2.11 on 2026-09-09 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0016_remove_empresa_conferencia3"),
        ("financeiro", "0001_initial"),
        ("prestacao", "0014_vincula_termos_prestacoes"),
        ("termos", "0017_alter_termos_extratosbancarios_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="movimentacaofinanceira",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gt", 0)),
                name="financeiro_valor_maior_que_zero",
            ),
        ),
    ]
