# Generated by Django 5.2.11 on 2026-09-10 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financeiro", "0002_movimentacaofinanceira_financeiro_valor_maior_que_zero"),
        ("lancamentos", "0003_lancamento_competencia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConciliacaoFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmado", "Confirmado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("decidido_em", models.DateTimeField(auto_now=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "decidido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conciliacoes_financeiras_decididas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lancamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conciliacoes_financeiras",
                        to="lancamentos.lancamento",
                    ),
                ),
                (
                    "movimentacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conciliacao_manual",
                        to="financeiro.movimentacaofinanceira",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conciliacao financeira",
                "verbose_name_plural": "Conciliacoes financeiras",
                "ordering": ("-decidido_em", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "confirmado")),
                        fields=("lancamento",),
                        name="financeiro_lancamento_confirmado_unico",
                    )
                ],
            },
        ),
    ]
