# Generated by Django 5.2.11 on 2026-09-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0016_remove_empresa_conferencia3"),
        ("financeiro", "0003_conciliacaofinanceira"),
        ("prestacao", "0014_vincula_termos_prestacoes"),
        ("termos", "0017_alter_termos_extratosbancarios_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaofinanceira",
            name="checknum",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="movimentacaofinanceira",
            name="data_hora_ofx",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movimentacaofinanceira",
            name="fitid",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="movimentacaofinanceira",
            name="memo_ofx",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="movimentacaofinanceira",
            name="ordem_ofx",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movimentacaofinanceira",
            name="tipo_ofx",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="movimentacaofinanceira",
            name="valor_ofx",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.CreateModel(
            name="ImportacaoOFX",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_arquivo", models.CharField(max_length=255)),
                ("hash_arquivo", models.CharField(db_index=True, max_length=64)),
                ("banco", models.CharField(blank=True, max_length=20)),
                ("conta_mascarada", models.CharField(blank=True, max_length=64)),
                ("tipo_conta", models.CharField(blank=True, max_length=20)),
                ("moeda", models.CharField(blank=True, max_length=3)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "saldo_informado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("data_saldo", models.DateField(blank=True, null=True)),
                ("quantidade_movimentos", models.PositiveIntegerField(default=0)),
                ("importado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="importacoes_ofx",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "importado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="importacoes_ofx",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="importacoes_ofx",
                        to="prestacao.prestacao",
                    ),
                ),
                (
                    "termo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="importacoes_ofx",
                        to="termos.termos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Importacao OFX",
                "verbose_name_plural": "Importacoes OFX",
                "ordering": ("-importado_em", "-id"),
            },
        ),
        migrations.AddField(
            model_name="movimentacaofinanceira",
            name="importacao_ofx",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimentos",
                to="financeiro.importacaoofx",
            ),
        ),
        migrations.AddConstraint(
            model_name="importacaoofx",
            constraint=models.UniqueConstraint(
                fields=("empresa", "termo", "hash_arquivo"),
                name="financeiro_ofx_arquivo_unico_por_termo",
            ),
        ),
    ]
