# Generated by Django 5.2.11 on 2026-09-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financeiro", "0004_movimentacaofinanceira_checknum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaofinanceira",
            name="hash_movimento",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
