# Generated by Django 5.2.11 on 2026-09-23 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0016_remove_empresa_conferencia3"),
        ("financeiro", "0005_movimentacaofinanceira_hash_movimento"),
        ("prestacao", "0014_vincula_termos_prestacoes"),
        ("termos", "0017_alter_termos_extratosbancarios_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="movimentacaofinanceira",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hash_movimento", ""), _negated=True),
                fields=("empresa", "termo", "hash_movimento"),
                name="financeiro_ofx_movimento_unico_por_termo",
            ),
        ),
    ]
