# Generated by Django 5.2.11 on 2026-09-23 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "financeiro",
            "0006_movimentacaofinanceira_financeiro_ofx_movimento_unico_por_termo",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaofinanceira",
            name="movimento_relacionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentos_relacionados",
                to="financeiro.movimentacaofinanceira",
            ),
        ),
    ]
