# Generated by Django 3.0.6 on 2021-01-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_receitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='receitas',
        ),
    ]
