# Generated by Django 3.0.6 on 2021-01-26 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0006_auto_20210126_0123'),
        ('empresas', '0004_empresa_receitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='termos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='termos.Termos'),
        ),
    ]
