# Generated by Django 4.2.2 on 2023-06-20 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia3', '0002_remove_conferencia3_empresa_conferencia3_user_and_more'),
        ('empresas', '0005_empresa_termos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='receitas',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='termos',
        ),
        migrations.AddField(
            model_name='empresa',
            name='conferencia3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='conferencia3.conferencia3'),
        ),
    ]
