# Generated by Django 5.1.4 on 2025-01-05 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_remove_empresa_receitas_remove_empresa_termos_and_more'),
        ('termos', '0013_auto_20210130_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='termos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='termos.termos'),
        ),
    ]
