# Generated by Django 5.1.4 on 2025-01-05 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_termos'),
        ('prestacao', '0007_alter_prestacao_numtermo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='prestacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prestacao.prestacao'),
        ),
    ]
