# Generated by Django 5.1.4 on 2025-01-05 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_empresa_prestacao'),
        ('receitas', '0012_remove_receitas_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='receitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='receitas.receitas'),
        ),
    ]
