# Generated by Django 5.1.4 on 2025-01-05 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_curso_obs'),
        ('empresas', '0010_empresa_parcerias'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curso.curso'),
        ),
    ]
