# Generated by Django 5.2.11 on 2026-07-24 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0012_alter_empresa_parcerias"),
        ("termos", "0017_alter_termos_extratosbancarios_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="termos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="empresas_legadas",
                related_query_name="empresa_legada",
                to="termos.termos",
                verbose_name="Termo legado",
            ),
        ),
    ]
