# Generated by Django 5.2.11 on 2026-07-30 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conferencia3", "0009_remove_conferencia3_departamento_and_more"),
        ("curso", "0002_alter_curso_obs"),
        ("empresas", "0014_alter_empresa_prestacao"),
        ("receitas", "0012_remove_receitas_departamento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresa",
            options={
                "ordering": ["nome"],
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.AlterField(
            model_name="empresa",
            name="conferencia3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="empresas_legadas",
                to="conferencia3.conferencia3",
                verbose_name="Conferência legada",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="empresas_legadas",
                to="curso.curso",
                verbose_name="Curso legado",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="receitas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="empresas_legadas",
                to="receitas.receitas",
                verbose_name="Receita legada",
            ),
        ),
    ]
