# Generated by Django 5.2.11 on 2026-09-08 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0015_alter_empresa_options_alter_empresa_conferencia3_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="conferencia3",
        ),
    ]
