# Generated by Django 5.1.4 on 2025-01-05 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_empresa_receitas'),
        ('parcerias', '0008_remove_parcerias_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='parcerias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parcerias.parcerias'),
        ),
    ]
