# Generated by Django 5.2.11 on 2026-09-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lancamentos", "0002_glosas_sprint16"),
        ("prestacao", "0012_competenciaprestacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamento",
            name="competencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lancamentos",
                related_query_name="lancamento",
                to="prestacao.competenciaprestacao",
                verbose_name="Competência",
            ),
        ),
    ]
