# Generated by Django 3.0.6 on 2020-12-29 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('termos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termos',
            name='assinatura',
            field=models.DateField(blank=True, null=True, verbose_name='Assinatura'),
        ),
        migrations.AlterField(
            model_name='termos',
            name='nomemunicipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Beneficiários'),
        ),
        migrations.AlterField(
            model_name='termos',
            name='numdispensa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Dispensa'),
        ),
        migrations.AlterField(
            model_name='termos',
            name='parcelasAbertas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parcelas Abertas'),
        ),
        migrations.AlterField(
            model_name='termos',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
