# Generated by Django 4.2.3 on 2026-03-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("termos", "0014_remove_termos_departamentos"),
    ]

    operations = [
        migrations.AddField(
            model_name="termos",
            name="analista",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Analista"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="apelido",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Apelido"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="extratosBancarios",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Extratos Bancários)",
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="glosasRestituidas",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Glosas Restituídas)",
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="inicioVigencia",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Início Vigência"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="lacamentosGlosados",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Lançamentos Glosados)",
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="lacamentosIrregulares",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Lançamentos Irregulares)",
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="lacamentosNaoEnviados",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Lançamentos Não Enviados)",
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="lacamentosRegulares",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Lançamentos Regulares)",
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="naoanalisados",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Lançamentos Não Analisados)",
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="objeto",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Objeto"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="observacoes",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Observações)"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="parceria",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Parceria"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="pendenciasOfx",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Pendências OFX)"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="relatoriosDeSinteses",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Relatórios de Sínteses",
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="rendimento",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Rendimento"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="saldoContaSinteseDespesas",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Saldo Conta (Síntese Despesas)",
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="saldoContaSinteseMovFinanceira",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Saldo Conta (Síntese Mov. Financeira)",
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="saldoDashboard",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Saldo (Dashboard)"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="saldoFinal",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Saldo Final)"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="saldoGlosas",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Saldo Glosas)"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="status",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Status"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="terminoVigencia",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Término Vigência"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="termo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Termo"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="tipo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tipo"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="total",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Total)"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="totalDeLacamentos",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Total de Lançamentos)",
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="valorDevolvido",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Valor Devolvido)"
            ),
        ),
        migrations.AddField(
            model_name="termos",
            name="valoresGlosados",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Valores Glosados)"
            ),
        ),
    ]
