# Generated by Django 5.2.11 on 2026-07-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("termos", "0016_termos_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termos",
            name="extratosBancarios",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Extratos Bancários"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="glosasRestituidas",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Glosas Restituídas"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="lacamentosGlosados",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Lançamentos Glosados"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="lacamentosIrregulares",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                verbose_name="Lançamentos Irregulares",
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="lacamentosNaoEnviados",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                verbose_name="Lançamentos Não Enviados",
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="lacamentosRegulares",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                verbose_name="Lançamentos Regulares",
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="naoanalisados",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                verbose_name="Lançamentos Não Analisados",
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="numdispensa",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Nº Dispensa"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="numpa",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Nº do P.A."
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="numtermo",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Nº Termo"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="observacoes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="termos",
            name="parcelasAbertas",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Parcelas Abertas"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="pendenciasOfx",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Pendências OFX"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="saldoFinal",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Saldo Final"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="saldoGlosas",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Saldo Glosas"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="total",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Total"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="totalDeLacamentos",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Total de Lançamentos"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="valorDevolvido",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Valor Devolvido"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="valoresGlosados",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Valores Glosados"
            ),
        ),
        migrations.AlterField(
            model_name="termos",
            name="vigencia",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Vigência"
            ),
        ),
    ]
