# Generated by Django 5.2.11 on 2026-10-02 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departamentos", "0003_departamento_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="departamento",
            name="superior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subunidades",
                to="departamentos.departamento",
                verbose_name="Unidade superior",
            ),
        ),
        migrations.AddField(
            model_name="departamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("departamento", "Departamento"),
                    ("gabinete", "Gabinete"),
                    ("assessoria", "Assessoria"),
                    ("subsecretaria", "Subsecretaria"),
                    ("superintendencia", "Superintendencia"),
                    ("diretoria", "Diretoria"),
                    ("gerencia", "Gerencia"),
                ],
                default="departamento",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="departamento",
            name="nome",
            field=models.CharField(max_length=150),
        ),
    ]
