# Generated by Django 3.0.6 on 2020-12-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcerias', '0002_auto_20201228_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcerias',
            options={'ordering': ['numtermo']},
        ),
    ]
