# Generated by Django 3.0.6 on 2021-01-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcerias', '0003_auto_20201228_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcerias',
            name='empresa',
        ),
        migrations.AddField(
            model_name='parcerias',
            name='concluido',
            field=models.BooleanField(default=1, verbose_name='Concluído'),
            preserve_default=False,
        ),
    ]
