# Generated by Django 3.0.6 on 2021-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcerias', '0004_auto_20210128_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcerias',
            name='concluido',
            field=models.BooleanField(blank=True, null=True, verbose_name='Concluído'),
        ),
    ]
