# Generated by Django 3.0.6 on 2021-01-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcerias', '0006_auto_20210128_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcerias',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
    ]
