# Generated by Django 5.2.11 on 2026-07-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcerias", "0009_parcerias_empresa_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcerias",
            name="historico",
            field=models.TextField(blank=True, null=True, verbose_name="Histórico"),
        ),
    ]
