# Generated by Django 5.2.11 on 2026-09-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fornecedores", "0004_alter_fornecedores_credor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedores",
            name="codigo_pseudonimo",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Código pseudonimizado",
            ),
        ),
    ]
