# Generated by Django 5.2.11 on 2026-09-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fornecedores", "0006_preencher_codigos_pseudonimos"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedores",
            name="documento_normalizado",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=14,
                null=True,
                unique=True,
                verbose_name="Documento normalizado",
            ),
        ),
    ]
