# Generated by Django 3.0.6 on 2020-12-29 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0002_auto_20201228_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termos',
            name='departamentos',
        ),
        migrations.RemoveField(
            model_name='termos',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='termos',
            name='user',
        ),
    ]
