# Generated by Django 3.0.6 on 2021-01-25 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestacao', '0003_auto_20210125_1846'),
        ('departamentos', '0002_remove_departamento_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('termos', '0004_remove_termos_prestacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='termos',
            name='departamentos',
            field=models.ManyToManyField(to='departamentos.Departamento'),
        ),
        migrations.AddField(
            model_name='termos',
            name='prestacao',
            field=models.ManyToManyField(to='prestacao.Prestacao'),
        ),
        migrations.AddField(
            model_name='termos',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
