# Generated by Django 3.0.6 on 2021-01-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0005_auto_20210125_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termos',
            name='user',
        ),
        migrations.AlterField(
            model_name='termos',
            name='valorglobal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Global'),
        ),
        migrations.AlterField(
            model_name='termos',
            name='valorrepasse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Repassado'),
        ),
        migrations.AlterField(
            model_name='termos',
            name='valorsaldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Saldo'),
        ),
    ]
