# Generated by Django 3.0.6 on 2021-01-30 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0009_remove_termos_prestacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='documentos')),
                ('pertence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='termos.Termos')),
            ],
        ),
    ]
