# Generated by Django 3.0.6 on 2021-01-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0011_auto_20210130_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termos',
            old_name='descricaoTermos',
            new_name='descricao',
        ),
    ]
