# Generated by Django 3.0.6 on 2021-01-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0012_auto_20210130_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termos',
            name='arquivoTermos',
        ),
        migrations.RemoveField(
            model_name='termos',
            name='descricao',
        ),
    ]
