# Generated by Django 5.1.4 on 2025-01-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0013_auto_20210130_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termos',
            name='departamentos',
        ),
    ]
