# Generated by Django 3.0.6 on 2021-01-30 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0011_auto_20210130_1843'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivoTermos',
            field=models.FileField(default=1, upload_to='termos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='pertenceTermos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='termos.Termos'),
            preserve_default=False,
        ),
    ]
