# Generated by Django 3.0.6 on 2021-01-30 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0013_auto_20210130_1942'),
        ('documentos', '0006_remove_documento_pertence1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='pertence',
        ),
        migrations.AddField(
            model_name='documento',
            name='numtermo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='termos.Termos'),
            preserve_default=False,
        ),
    ]
