# Generated by Django 3.0.6 on 2022-02-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohoraextra',
            name='empresa',
        ),
        migrations.AddField(
            model_name='registrohoraextra',
            name='funcionario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assunto'),
        ),
    ]
