# Generated by Django 3.0.6 on 2020-12-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('termos', '0001_initial'),
        ('departamentos', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], max_length=50, verbose_name='Parcela')),
                ('ordem', models.CharField(max_length=5, verbose_name='Ordem')),
                ('rubricaNivel1', models.CharField(choices=[('1 - pessoal e encargos sociais', '1 - Pessoal e Encargos Sociais'), ('2 - gêneros alimentícios', '2 - Gêneros Alimentícios'), ('3 - material consumo', '3 - Material Consumo'), ('4 - custos indiretos', '4 - Custos Indiretos')], max_length=100, verbose_name='Rubrica Nível 1')),
                ('rubricaNivel2', models.CharField(choices=[('1.1 - pagamento de remunueração', '1.1 - Pagamento de Remuneração'), ('1.2 - pagamento de encargos sociais, tributos e benefícios', '1.2 - Pagamento de Encargos Sociais, Tributos e Benefícios'), ('2.1 - gêneros de alimentação', '2.1 - Gêneros de Alimentação'), ('3.1 - epi´s', '3.1 - Epi´s'), ('3.2 - material de limpeza', '3.2 - Material de Limpeza'), ('3.3 - material descartável', '3.3 - Material Descartáve'), ('3.4 - material de copa e cozinha', '3.4 - Material de Copa e Cozinha'), ('3.5 - material de higiene dos gêneros alimentícios', '3.5 - Material de Higiene dos Gêneros Alimentícios'), ('3.6 - material de expediente', '3.6 - Material de Expediente'), ('4.1 - serviços de departamento pessoal e medicina do trabalho', '4.1 - Serviços de Departamento Pessoal e Medicina do Trabalho'), ('4.2 - serviços de telefonia', '4.2 - Serviços de Telefonia'), ('4.3 - serviços gráficos e comunicação', '4.3 - Serviços Gráficos e Comunicação'), ('4.4 - serviço de manutenção e conservação (imóveis)', '4.4 - Serviço de Manutenção e Conservação (Imóveis)'), ('4.5 - serviço de manutenção e conservação (máquinas e equipamentos)', '4.5 - Serviço de Manutenção e Conservação (Máquinas e Equipamentos)'), ('4.6 - locação de máquinas e equipamentos', '4.6 - Locação de Máquinas e Equipamentos'), ('4.7 - locação de imóveis', '4.7 - Locação de Imóveis'), ('4.8 - gás', '4.8 - Gás'), ('4.9 - energia elétrica', '4.9 - Energia Elétrica'), ('4.10 - despesa com pessoal indireto', '4.10 - Despesa com Pessoal Indireto')], max_length=100, verbose_name='Rubrica Nível 2')),
                ('rubricaNivel3', models.CharField(choices=[('1.1.1 - 13º salário', '1.1.1 - 13º Salário'), ('1.1.2 - adicional de férias', '1.1.2 - Adicional de Férias'), ('1.1.3 - férias', '1.1.3 - Férias'), ('1.1.4 - aviso prévio indenizado', '1.1.4 - Aviso Prévio Indenizado'), ('1.2.1 - inss', '1.2.1 - INSS'), ('1.2.2 - fgts', '1.2.2 - FGTS'), ('1.2.3 - pis/pasep', '1.2.3 - PIS/PASEP'), ('1.2.4 - ausência remunerada', '1.2.4 - Ausência Remunerada'), ('1.2.5 - licenças', '1.2.5 - Licenças'), ('1.2.6 - vale transporte', '1.2.6 - Vale Transporte'), ('1.2.7 - outros benefícios', '1.2.7 - Outros Benefícios'), ('1.9.9 - outros - pessoal e encargos sociais', '1.9.9 - Outros - Pessoal e Encargos Sociais'), ('2.9.9 - outros - gêneros alimentícios', '2.9.9 - Outros Gêneros Alimentícios'), ('3.9.9 - outros - material consumo', '3.9.9 - Outros Material Consumo'), ('4.9.9 - outros - custos indiretos', '4.9.9 - Outros Custos Indiretos')], max_length=100, verbose_name='Rubrica Nível 3')),
                ('outrobeneficio', models.CharField(db_column='outroBeneficio', max_length=100, verbose_name='Especificar Outro')),
                ('tipo', models.CharField(choices=[('cnpj', 'CNPJ'), ('cpf', 'CPF')], max_length=50, verbose_name='Tipo')),
                ('CpfCnpj', models.CharField(max_length=50, verbose_name='CPF/CNPJ')),
                ('especie', models.CharField(choices=[('BOLETO', 'Boleto'), ('Trct', 'TRCT'), ('Nfs-e', 'NFS-e'), ('FAT. LOCAÇÃO', 'Fat. Locação'), ('RECIBO', 'Recibo')], max_length=50, verbose_name='Especie')),
                ('numero', models.CharField(max_length=15, verbose_name='Numero')),
                ('data', models.DateField(verbose_name='Data')),
                ('comprovante', models.CharField(max_length=50, verbose_name='Comprovante')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Separar centavos com . (ponto)', max_digits=10, verbose_name='Valor')),
                ('fileBoleto', models.FileField(blank=True, null=True, upload_to='prestacao_photos', verbose_name='Boleto')),
                ('fileNF', models.FileField(blank=True, null=True, upload_to='prestacao_photos', verbose_name='Nota Fiscal')),
                ('fileComprPag', models.FileField(blank=True, null=True, upload_to='prestacao_photos', verbose_name='Comprovante de Pagamento')),
                ('fileOrcamentos', models.FileField(blank=True, null=True, upload_to='prestacao_photos', verbose_name='Orçamentos')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='prestacao_photos')),
                ('conferido', models.BooleanField(verbose_name='Conferido')),
                ('notificado', models.BooleanField(verbose_name='Notificado')),
                ('aprovado', models.BooleanField(verbose_name='Aprovado')),
                ('notificacao', models.TextField(verbose_name='Notificações')),
                ('credor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fornecedores.Fornecedores')),
                ('departamento', models.ManyToManyField(to='departamentos.Departamento')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
                ('numtermo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='termos.Termos')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
