# Generated by Django 4.2.2 on 2023-06-20 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferencia3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencia3',
            name='empresa',
        ),
        migrations.AddField(
            model_name='conferencia3',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conferencia3',
            name='especie',
            field=models.CharField(choices=[('1ª parcela 13º salário', '1ª Parcela 13º Salário'), ('2ª parcela 13º salário', '2ª Parcela 13º Salário'), ('boleto', 'Boleto'), ('danfe', 'DANFE'), ('trct', 'Trct'), ('fat. Locação', 'Fat. Locação'), ('fatura', 'Fatura'), ('férias', 'Férias'), ('fgts', 'FGTS'), ('gps', 'GPS'), ('grrf', 'GRRF'), ('guia darf', 'Guia Darf'), ('guia fgts', 'Guia FGTS'), ('guia gps', 'Guia GPS'), ('guia issqn', 'Guia ISSQN'), ('nf', 'NF'), ('nfs-e', 'NFS-e'), ('recibo', 'Recibo'), ('recibo férias', 'Recibo Férias'), ('recibo pagto', 'Recibo Pagto'), ('reembolso de passivo', 'Reembolso de Passivo'), ('tarifa bancária', 'Tarifa Bancária'), ('trct', 'TRCT'), ('trct dissídio', 'TRCT Dissídio')], max_length=50, verbose_name='Especie'),
        ),
    ]
