# Generated by Django 4.2.2 on 2023-07-01 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia3', '0002_remove_conferencia3_empresa_conferencia3_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencia3',
            name='departamento',
        ),
    ]
