# Generated by Django 4.2.2 on 2023-07-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia3', '0003_remove_conferencia3_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia3',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
