# Generated by Django 5.1.4 on 2025-01-03 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia3', '0004_alter_conferencia3_id'),
        ('funcionarios', '0019_remove_funcionario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia3',
            name='nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
        ),
    ]
