# Generated by Django 5.1.4 on 2025-01-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia3', '0008_conferencia3_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencia3',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='conferencia3',
            name='nome',
        ),
    ]
