# Generated by Django 3.0.6 on 2021-01-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestacao', '0003_auto_20210125_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacao',
            name='user',
        ),
    ]
