# Generated by Django 3.0.6 on 2021-01-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestacao', '0004_remove_prestacao_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestacao',
            options={'ordering': ['numtermo', 'tipoTermo']},
        ),
        migrations.RenameField(
            model_name='prestacao',
            old_name='numTermo',
            new_name='numtermo',
        ),
    ]
