# Generated by Django 3.0.6 on 2021-01-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0009_remove_termos_prestacao'),
        ('prestacao', '0005_auto_20210127_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacao',
            name='numtermo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='termos.Termos'),
        ),
    ]
