# Generated by Django 5.1.4 on 2025-01-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestacao', '0007_alter_prestacao_numtermo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacao',
            name='departamentos',
        ),
    ]
