# Generated by Django 5.2.11 on 2026-09-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prestacao", "0011_alter_historicoprestacao_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetenciaPrestacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveSmallIntegerField(verbose_name="Ano")),
                ("mes", models.PositiveSmallIntegerField(verbose_name="Mês")),
                ("data_inicial", models.DateField(verbose_name="Data inicial")),
                ("data_final", models.DateField(verbose_name="Data final")),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Saldo inicial",
                    ),
                ),
                (
                    "saldo_final",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Saldo final",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("em_analise", "Em análise"),
                            ("concluida", "Concluída"),
                        ],
                        default="aberta",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competencias",
                        to="prestacao.prestacao",
                        verbose_name="Prestação de contas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competência da prestação",
                "verbose_name_plural": "Competências da prestação",
                "ordering": ["ano", "mes"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prestacao", "ano", "mes"),
                        name="competencia_unica_por_prestacao",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("mes__gte", 1), ("mes__lte", 12)),
                        name="competencia_mes_valido",
                    ),
                ],
            },
        ),
    ]
