# Generated by Django 5.2.11 on 2026-09-05 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prestacao", "0012_competenciaprestacao"),
        ("termos", "0017_alter_termos_extratosbancarios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacao",
            name="termo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prestacoes_do_termo",
                related_query_name="prestacao_do_termo",
                to="termos.termos",
                verbose_name="Termo",
            ),
        ),
    ]
