# Generated by Django 3.0.6 on 2021-01-16 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osc', models.CharField(max_length=30, verbose_name='OSC')),
                ('parcela', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, verbose_name='Parcela')),
                ('ente', models.CharField(choices=[('municipal', 'Municipal'), ('estadual', 'Estadual'), ('federal', 'Federal')], max_length=10, verbose_name='Ente')),
                ('fonte', models.CharField(max_length=5, verbose_name='Fonte')),
                ('conta', models.CharField(max_length=10, verbose_name='Conta')),
                ('data', models.DateField(verbose_name='Data')),
                ('saldoAnterior', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Saldo Anterior')),
                ('repasse', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Repasse - NAP')),
                ('depositoOsc', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Depósito OSC')),
                ('rendimento', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Rendimento Aplicação')),
                ('creditoAutorizado', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Crédito Autorizado')),
                ('resgateAutomatico', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Resgate Automático')),
                ('estorno', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Estorno')),
                ('totalReceitas', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Receitas')),
                ('aplicacao', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Aplicação Financeira')),
                ('debitoAutorizado', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Débito Autorizado')),
                ('despesaBancaria', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Despesa Bancária')),
                ('impostoRenda', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='IR')),
                ('iof', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='IOF')),
                ('despesas', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Pagamentos')),
                ('totalDespesas', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Despesas')),
                ('saldoBancario', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Saldo Final')),
                ('fileNap', models.FileField(blank=True, null=True, upload_to='receitas_fotos', verbose_name='NAP')),
                ('fileDepositoTicket', models.FileField(blank=True, null=True, upload_to='receitas_fotos', verbose_name='Comprovante Depósito Tickets')),
                ('fileDepositoOsc', models.FileField(blank=True, null=True, upload_to='receitas_fotos', verbose_name='Comprovante Depósito OSC')),
                ('fileAplicacao', models.FileField(blank=True, null=True, upload_to='receitas_fotos', verbose_name='Comprovante de Aplicação Financeira')),
                ('fileContrapartida', models.FileField(blank=True, null=True, upload_to='receitas_fotos', verbose_name='Comprovante de Contrapartida')),
                ('fileEstorno', models.FileField(blank=True, null=True, upload_to='receitas_fotos', verbose_name='Comprovante de Estorno')),
                ('conferido', models.BooleanField(verbose_name='Conferido')),
                ('notificado', models.BooleanField(verbose_name='Notificado')),
                ('aprovado', models.BooleanField(verbose_name='Aprovado')),
                ('notificacao', models.CharField(max_length=500, verbose_name='Notificações')),
                ('departamento', models.ManyToManyField(to='departamentos.Departamento')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
