# Generated by Django 3.0.6 on 2021-01-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='receitas',
            name='user',
        ),
        migrations.AlterField(
            model_name='receitas',
            name='aplicacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Aplicação Financeira'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='aprovado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Aprovado'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='conferido',
            field=models.BooleanField(blank=True, null=True, verbose_name='Conferido'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='creditoAutorizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Crédito Autorizado'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='debitoAutorizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Débito Autorizado'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='depositoOsc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Depósito OSC'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='despesaBancaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Despesa Bancária'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='despesas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Pagamentos'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='estorno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Estorno'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='impostoRenda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='IR'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='iof',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='IOF'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='notificacao',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Notificações'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='notificado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Notificado'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='rendimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Rendimento Aplicação'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='repasse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Repasse - NAP'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='resgateAutomatico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Resgate Automático'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='saldoAnterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Saldo Anterior'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='saldoBancario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Saldo Final'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='totalDespesas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total Despesas'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='totalReceitas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total Receitas'),
        ),
    ]
