# Generated by Django 3.0.6 on 2021-01-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_auto_20210119_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='departamento',
        ),
    ]
