# Generated by Django 3.0.6 on 2021-01-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_remove_receitas_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='repasse',
        ),
    ]
