# Generated by Django 3.0.6 on 2021-01-25 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0004_remove_termos_prestacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0002_remove_departamento_empresa'),
        ('receitas', '0006_receitas_repasse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receitas',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='receitas',
            name='departamento',
            field=models.ManyToManyField(to='departamentos.Departamento'),
        ),
        migrations.AddField(
            model_name='receitas',
            name='numtermo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='termos.Termos'),
        ),
        migrations.AddField(
            model_name='receitas',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
