# Generated by Django 3.0.6 on 2021-01-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0007_auto_20210125_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='user',
        ),
    ]
