# Generated by Django 3.0.6 on 2021-01-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0008_remove_receitas_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='empresa',
            field=models.CharField(default=1, max_length=30, verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
