# Generated by Django 5.1.4 on 2025-01-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia3', '0007_conferencia3_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia3',
            name='nome',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome Empresa'),
            preserve_default=False,
        ),
    ]
