# Generated by Django 5.2.11 on 2026-08-18 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("diligencias", "0001_initial"),
        ("documentos", "0010_documento_conferencia"),
        ("empresas", "0015_alter_empresa_options_alter_empresa_conferencia3_and_more"),
        ("lancamentos", "0002_glosas_sprint16"),
        ("prestacao", "0011_alter_historicoprestacao_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParecerTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, default="", max_length=50)),
                ("versao", models.PositiveIntegerField(default=1)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("EM_REVISAO", "Em revis?o"),
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado"),
                            ("SUBSTITUIDO", "Substitu?do"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_conclusao",
                    models.CharField(
                        choices=[
                            ("EM_ANALISE", "Em an?lise"),
                            ("SEM_PENDENCIAS_RELEVANTES", "Sem pend?ncias relevantes"),
                            ("COM_RESSALVAS", "Com ressalvas"),
                            ("COM_PENDENCIAS_SANEAVEIS", "Com pend?ncias sane?veis"),
                            ("COM_IRREGULARIDADES", "Com irregularidades"),
                            ("AGUARDANDO_DILIGENCIA", "Aguardando dilig?ncia"),
                            ("INCONCLUSIVO", "Inconclusivo"),
                        ],
                        default="EM_ANALISE",
                        max_length=40,
                    ),
                ),
                ("resumo_executivo", models.TextField(blank=True, default="")),
                ("fundamentacao_geral", models.TextField(blank=True, default="")),
                ("conclusao", models.TextField(blank=True, default="")),
                ("ressalvas", models.TextField(blank=True, default="")),
                ("recomendacoes_gerais", models.TextField(blank=True, default="")),
                ("elaborado_em", models.DateTimeField(auto_now_add=True)),
                ("revisado_em", models.DateTimeField(blank=True, null=True)),
                ("aprovado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pareceres_aprovados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "elaborado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pareceres_elaborados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pareceres_tecnicos",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pareceres_tecnicos",
                        to="prestacao.prestacao",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pareceres_revisados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "versao_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versoes_posteriores",
                        to="pareceres.parecertecnico",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-versao"],
            },
        ),
        migrations.CreateModel(
            name="ItemParecer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, default="", max_length=100)),
                (
                    "codigo_regra",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("DOCUMENTAL", "Documental"),
                            ("FINANCEIRA", "Financeira"),
                            ("PLANO_TRABALHO", "Plano de trabalho"),
                            ("RH", "Recursos humanos"),
                            ("LGPD", "LGPD"),
                            ("VIGENCIA", "Vig?ncia"),
                            ("OUTRA", "Outra"),
                        ],
                        default="DOCUMENTAL",
                        max_length=30,
                    ),
                ),
                (
                    "severidade",
                    models.CharField(
                        choices=[
                            ("INFORMATIVA", "Informativa"),
                            ("ALERTA", "Alerta"),
                            ("CRITICA", "Cr?tica"),
                        ],
                        default="ALERTA",
                        max_length=20,
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("PGP_RULES", "PGP Rules"),
                            ("IA_ASSISTIDA", "IA assistida"),
                            ("DILIGENCIA", "Dilig?ncia"),
                            ("OUTRA", "Outra"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, default="")),
                ("fato_verificado", models.TextField(blank=True, default="")),
                ("evidencia", models.TextField(blank=True, default="")),
                ("fundamentacao", models.TextField(blank=True, default="")),
                ("risco_glosa", models.TextField(blank=True, default="")),
                ("recomendacao", models.TextField(blank=True, default="")),
                ("manifestacao_analista", models.TextField(blank=True, default="")),
                (
                    "conclusao_item",
                    models.CharField(
                        choices=[
                            ("NAO_ANALISADO", "N?o analisado"),
                            ("REGULAR", "Regular"),
                            ("RESSALVA", "Ressalva"),
                            ("PENDENCIA_SANEAVEL", "Pend?ncia sane?vel"),
                            ("IRREGULARIDADE", "Irregularidade"),
                            ("SANADO", "Sanado"),
                            ("NAO_SANADO", "N?o sanado"),
                        ],
                        default="NAO_ANALISADO",
                        max_length=30,
                    ),
                ),
                (
                    "resultado_origem",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("origem_normativa", models.TextField(blank=True, default="")),
                ("dados_origem", models.JSONField(blank=True, default=dict)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_parecer_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diligencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_parecer",
                        to="diligencias.diligencia",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_parecer",
                        to="documentos.documento",
                    ),
                ),
                (
                    "lancamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_parecer",
                        to="lancamentos.lancamento",
                    ),
                ),
                (
                    "parecer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="pareceres.parecertecnico",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoParecer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.CharField(max_length=100)),
                (
                    "situacao_anterior",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "nova_situacao",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "conclusao_anterior",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "nova_conclusao",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("observacao", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historicos_parecer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parecer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="pareceres.parecertecnico",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="parecertecnico",
            constraint=models.UniqueConstraint(
                fields=("prestacao", "versao"), name="uniq_parecer_versao_prestacao"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemparecer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("codigo", ""), _negated=True),
                fields=("parecer", "codigo"),
                name="uniq_codigo_item_por_parecer",
            ),
        ),
    ]
