# Generated by Django 5.2.11 on 2026-08-19 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diligencias", "0001_initial"),
        ("documentos", "0010_documento_conferencia"),
        ("lancamentos", "0002_glosas_sprint16"),
        ("pareceres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenciaParecer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DOCUMENTO", "Documento"),
                            ("LANCAMENTO", "Lan?amento"),
                            ("DILIGENCIA", "Dilig?ncia"),
                            ("REGISTRO_SISTEMA", "Registro do sistema"),
                            ("DECLARACAO", "Declara??o"),
                            ("OUTRA", "Outra"),
                        ],
                        default="OUTRA",
                        max_length=30,
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "referencia_externa",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("dados_snapshot", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidencias_parecer_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diligencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidencias_parecer",
                        to="diligencias.diligencia",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidencias_parecer",
                        to="documentos.documento",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias_estruturadas",
                        to="pareceres.itemparecer",
                    ),
                ),
                (
                    "lancamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidencias_parecer",
                        to="lancamentos.lancamento",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FundamentacaoParecer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "esfera",
                    models.CharField(
                        choices=[
                            ("FEDERAL", "Federal"),
                            ("ESTADUAL", "Estadual"),
                            ("MUNICIPAL", "Municipal"),
                            ("INTERNA", "Norma interna"),
                            ("OUTRA", "Outra"),
                        ],
                        default="OUTRA",
                        max_length=20,
                    ),
                ),
                ("ente", models.CharField(blank=True, default="", max_length=255)),
                ("norma", models.CharField(max_length=255)),
                (
                    "dispositivo",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("descricao", models.TextField(blank=True, default="")),
                ("inicio_vigencia", models.DateField(blank=True, null=True)),
                ("fim_vigencia", models.DateField(blank=True, null=True)),
                ("origem", models.CharField(blank=True, default="", max_length=500)),
                ("dados_snapshot", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fundamentacoes_parecer_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundamentacoes_estruturadas",
                        to="pareceres.itemparecer",
                    ),
                ),
            ],
            options={
                "ordering": ["esfera", "norma", "dispositivo", "id"],
            },
        ),
    ]
