# Generated by Django 5.2.11 on 2026-09-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pareceres", "0002_evidenciaparecer_fundamentacaoparecer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidenciaparecer",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("DOCUMENTO", "Documento"),
                    ("LANCAMENTO", "Lançamento"),
                    ("DILIGENCIA", "Diligência"),
                    ("REGISTRO_SISTEMA", "Registro do sistema"),
                    ("DECLARACAO", "Declaração"),
                    ("OUTRA", "Outra"),
                ],
                default="OUTRA",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="itemparecer",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("DOCUMENTAL", "Documental"),
                    ("FINANCEIRA", "Financeira"),
                    ("PLANO_TRABALHO", "Plano de trabalho"),
                    ("RH", "Recursos humanos"),
                    ("LGPD", "LGPD"),
                    ("VIGENCIA", "Vigência"),
                    ("OUTRA", "Outra"),
                ],
                default="DOCUMENTAL",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="itemparecer",
            name="conclusao_item",
            field=models.CharField(
                choices=[
                    ("NAO_ANALISADO", "Não analisado"),
                    ("REGULAR", "Regular"),
                    ("RESSALVA", "Ressalva"),
                    ("PENDENCIA_SANEAVEL", "Pendência saneável"),
                    ("IRREGULARIDADE", "Irregularidade"),
                    ("SANADO", "Sanado"),
                    ("NAO_SANADO", "Não sanado"),
                ],
                default="NAO_ANALISADO",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="itemparecer",
            name="origem",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("PGP_RULES", "PGP Rules"),
                    ("IA_ASSISTIDA", "IA assistida"),
                    ("DILIGENCIA", "Diligência"),
                    ("OUTRA", "Outra"),
                ],
                default="MANUAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="itemparecer",
            name="severidade",
            field=models.CharField(
                choices=[
                    ("INFORMATIVA", "Informativa"),
                    ("ALERTA", "Alerta"),
                    ("CRITICA", "Crítica"),
                ],
                default="ALERTA",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="parecertecnico",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("EM_REVISAO", "Em revisão"),
                    ("FINALIZADO", "Finalizado"),
                    ("CANCELADO", "Cancelado"),
                    ("SUBSTITUIDO", "Substituído"),
                ],
                default="RASCUNHO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="parecertecnico",
            name="tipo_conclusao",
            field=models.CharField(
                choices=[
                    ("EM_ANALISE", "Em análise"),
                    ("SEM_PENDENCIAS_RELEVANTES", "Sem pendências relevantes"),
                    ("COM_RESSALVAS", "Com ressalvas"),
                    ("COM_PENDENCIAS_SANEAVEIS", "Com pendências saneáveis"),
                    ("COM_IRREGULARIDADES", "Com irregularidades"),
                    ("AGUARDANDO_DILIGENCIA", "Aguardando diligência"),
                    ("INCONCLUSIVO", "Inconclusivo"),
                ],
                default="EM_ANALISE",
                max_length=40,
            ),
        ),
    ]
