# Generated by Django 3.0.6 on 2020-12-28 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcerias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numParceria', models.CharField(blank=True, max_length=8, null=True, verbose_name='Parceria')),
                ('nomeOSC', models.CharField(blank=True, max_length=30, null=True, verbose_name='OSC')),
                ('fileTC', models.FileField(blank=True, null=True, upload_to='parcerias_photos', verbose_name='TC')),
                ('numRA', models.CharField(blank=True, max_length=12, null=True, verbose_name='RA')),
                ('numOficioRA', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ofício - RA')),
                ('fileRA', models.FileField(blank=True, null=True, upload_to='parcerias_photos', verbose_name='Relatório Auditoria (RA)')),
                ('fileOficioRA', models.FileField(blank=True, null=True, upload_to='parcerias_photos', verbose_name='Ofício RA')),
                ('dtRaSMDS', models.DateField(blank=True, null=True, verbose_name='Entrada RA')),
                ('respRA', models.CharField(blank=True, max_length=3, null=True, verbose_name='Resposta RA')),
                ('numRE', models.CharField(blank=True, max_length=12, null=True, verbose_name='RE')),
                ('numOficioRE', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ofício - RE')),
                ('fileRE', models.FileField(blank=True, null=True, upload_to='parcerias_photos', verbose_name='Relatório Efetividade (RE)')),
                ('fileOficioRE', models.FileField(blank=True, null=True, upload_to='parcerias_photos', verbose_name='Ofício RE')),
                ('dtReSMDS', models.DateField(blank=True, null=True, verbose_name='Entrada RE')),
                ('respRE', models.CharField(blank=True, max_length=3, null=True, verbose_name='Resposta RE')),
                ('fileRRE', models.FileField(blank=True, null=True, upload_to='parcerias_photos', verbose_name='Resposta RE')),
                ('prazoFinal', models.CharField(blank=True, max_length=12, null=True, verbose_name='Prazo Final')),
                ('status', models.TextField(blank=True, null=True, verbose_name='Status')),
                ('prazoDecorrido', models.CharField(blank=True, max_length=8, null=True, verbose_name='Prazo Decorrido')),
                ('prazoRestante', models.CharField(blank=True, max_length=8, null=True, verbose_name='Prazo Restante')),
                ('historico', models.TextField(blank=True, null=True, verbose_name='Histórico ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parcerias_photos')),
                ('departamento', models.ManyToManyField(to='departamentos.Departamento')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nomeOSC'],
            },
        ),
    ]
