# Generated by Django 3.0.6 on 2020-12-28 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('parcerias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcerias',
            name='numParceria',
        ),
        migrations.AddField(
            model_name='parcerias',
            name='credor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fornecedores.Fornecedores'),
        ),
        migrations.AddField(
            model_name='parcerias',
            name='numtermo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='termos.Termos'),
        ),
    ]
