# Generated by Django 5.1.4 on 2025-01-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcerias', '0007_auto_20210129_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcerias',
            name='departamento',
        ),
    ]
