# Generated by Django 5.2.11 on 2026-08-13 02:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atualizacaometa",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Atualização da meta",
                "verbose_name_plural": "Atualizações das metas",
            },
        ),
        migrations.AlterModelOptions(
            name="metaexecucao",
            options={
                "ordering": ["prestacao", "codigo", "titulo"],
                "verbose_name": "Meta de execução",
                "verbose_name_plural": "Metas de execução",
            },
        ),
    ]
