# Generated by Django 3.0.6 on 2021-01-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20210130_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='arquivoTermos',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='pertenceTermos',
        ),
    ]
