# Generated by Django 3.0.6 on 2021-01-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_documento_pertence1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='pertence1',
        ),
    ]
