# Generated by Django 3.0.6 on 2021-01-30 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_auto_20210130_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='numtermo',
            new_name='pertence',
        ),
    ]
